### ISSUE TITLE
Superclass docstring not used when subclass docstring omitted

### ISSUE THREAD

**Issue by joelberkeley-secondmind** [readthedocs/sphinx-autoapi#218]
If I override a method, but omit the docstring, I would like autoapi to use the docstring of the superclass method, e.g.
```python3
class Foo:
    def bar():
        """ frobnicate """
        ...

class Baz(Foo):
    def bar():  # i'd expect the docs for `Baz.bar` to default to the same as `Foo.bar` i.e. """ frobnicate """
        ...
```
especially where the superclass method is abstract and so it expected to be overridden.

I've tried
```python3
autoapi_options = [
    ...,
    'inherited-members',
]
```
but that just inherits docstrings for methods that _aren't_ overridden (which is what I expected, but doesn't solve my problem)

**Comment by AWhetter** [comment]
Which version of AutoAPI are you using? This should have been fixed in v1.4.0 (fca36aa66493b8b90f9c9c6efb9bd98269734610).

**Comment by joelberkeley-pio** [comment]
I was using 1.3.0, but I updated to 1.4.0 and I'm still seeing the problem (even though other things have changed like there are now summary tables). I've also updated sphinx (from 3.0.4 to 3.1.0) with no change

**Comment by joelberkeley-pio** [comment]
I've found that it works for some methods, but not for others. I will look into what the difference is

**Comment by joelberkeley-pio** [comment]
OK, I've narrowed it down. When the superclass is generic
```python
class Foo(Generic[T]):
    def bar() -> T:
        """ frobnicate """
        ...
```
and the subclass specifies the generic type
```python
class Baz(Foo[int]):
    def bar() -> int:
        ...
```
i _don't_ get the docstring in the subclass. If I leave out the type in the superclass
```python
class Baz(Foo):
    def bar() -> int:
        ...
```
I do get the docstring in the subclass

**Comment by joelberkeley-pio** [comment]
On line 539 of that PR, there is
```
     if doc is None and isinstance(node.parent, astroid.nodes.ClassDef): 
```
perhaps that breaks when `Generic` is involved.
```
>>> type(Foo[int])
<class 'typing._GenericAlias'>
```

**Comment by AWhetter** [comment]
I'm not able to reproduce this. Please can you try with the latest master branch. I'm using the following example:

```python
from typing import Generic

class SomeGeneric(Generic[T]):
    def get_instance(self) -> T:
        """Get an instance of something."""

class SubGeneric(SomeGeneric[int]):
    def get_instance(self) -> int:
        pass
```
